name: flutter_osrm
description: A wrapper for the Open Source Routing Machine designed for Flutter
  including optional extra functionality for flutter_map
version: 0.1.0
homepage: null

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  
  async: ^2.9.0
  collection: ^1.16.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  latlong2: ^0.8.0
  meta: ^1.8.0
  polylabel: ^1.0.1
  positioned_tap_detector_2: ^1.0.4
  proj4dart: ^2.1.0
  routing_client_dart: ^0.3.2
  tuple: ^2.0.0
  vector_math: ^2.1.2
  flutter_osrm:
    git:
      url: https://github.com/rezaafallah/flutter_osrm.git
      # path: flutter_osrm
      
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  test: ^1.21.4
